### ISSUE TITLE
Have a way of removing locks once `Merge()` operations are complete.

### ISSUE THREAD

**Issue by cphang99** [git-depend/git-depend#15]
`Merge()` in the `Requests` object writes locks but doesn't remove them once git operations are complete.

This could be implemented by having a `RemoveLocks()` function in the `Requests` object to remove git notes corresponding to a lock.

**Comment by finn-ball** [comment]
Interesting to note(!) that a note is associated with a commit. So if we lock the current HEAD, merge our changes with a new commit, then the new commit will not have a lock note associated with it.

**Comment by cphang99** [comment]
> Interesting to note(!) that a note is associated with a commit. So if we lock the current HEAD, merge our changes with a new commit, then the new commit will not have a lock note associated with it.

This is true, so I think we need to use `git notes list` (or just `git notes`) to retrieve the mapping of notes of commits
```
022d2a7fa1de9b5c48f8834aad4022c54844adc6 037ca428f25493a2f5130303bf50543499f3f09f
238717f834a8b8ab620027681c1fdc6af7b45873 037dfc22fa09aeee17db1a466aea6b4233a21cb4
```
which is a text file listing the refs of the git notes, to the refs that the notes are annotating.

So I think there are a few questions that flow out of this:

- Should we have an invariant where the size of `refs/notes/commits` (or in this case `refs/notes/git-depend-lock`) is 1? That might faciliate cheaper ways of testing whether a git repository is safe to write to.
-  Should `git.Cache` should be storing this information, and updating this on a regular basis? I believe this to be true.
- Should removing locks essentially be manipulating this file (probably via `git notes remove <ref>`), and then pushing as the underlying mechanism?

**Comment by finn-ball** [comment]
> Should git.Cache should be storing this information, and updating this on a regular basis? I believe this to be true.

Yes, always fetch before we attempt to lock!

> Should removing locks essentially be manipulating this file (probably via git notes remove <ref>), and then pushing as the underlying mechanism?

Yes, push a remove.

> Should we have an invariant where the size of refs/notes/commits (or in this case refs/notes/git-depend-lock) is 1? That might faciliate cheaper ways of testing whether a git repository is safe to write to.

Not sure I understand this. Can you explain it a bit more?

**Comment by finn-ball** [comment]
Very quickly. If I have a repository where I add a note, N, and push. I then append to the note so it is now N' and push again. If I have a repository which is out of sync and tries to remove N by pushing the change, I would expect the push to fail. Is this true?

**Comment by finn-ball** [comment]
Is the note sha the same if you commit the same note?

**Comment by finn-ball** [comment]
> This is true, so I think we need to use git notes list (or just git notes) to retrieve the mapping of notes of commits
> ```
> 022d2a7fa1de9b5c48f8834aad4022c54844adc6 037ca428f25493a2f5130303bf50543499f3f09f
> 238717f834a8b8ab620027681c1fdc6af7b45873 037dfc22fa09aeee17db1a466aea6b4233a21cb4
> ```

Perhaps split this issue up and solve this part for #22

**Comment by cphang99** [comment]
So I think to close this out, my suggestion would be to do so via the following approach:

1. Provide a mechanism to determine the current SHA a lock resides at for a given repo. My sense right now is to do this with an extra method `ListLock()` for the `Lock` object that updates the current status of the branch and updates the local repo. I think that provides the simplest semantics.
2. Add a `RemoveLock()`  method that calls `ListLock()`, removes the git note at the correct ref, and pushes. This will need to be done optimistically, as we will need to deal with the case where 2 clients will attempt to remove the same note.
3. Update `Merge()` to use `RemoveLock()`

> Is the note sha the same if you commit the same note?

No it shouldn't be the same, I will test and confirm.

> Perhaps split this issue up and solve this part for #22

Happy to track 1. separately in #22 and close that out in a single PR, I suspect that 1. 2. and 3. can be done each as single PRs.

@finn-ball let me know if I've missed anything/if you disagree with the above approach. Otherwise I'll get cracking with this!
